# version: "3.9"

services:
  db:
    image: postgres
    container_name: db_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin

  app_dev:
    container_name: app_dev_container
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db:
  pgadmin:
  node_modules:
