FROM node:20.11.0

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

RUN npx prisma generate
CMD ["yarn","run", "dev"]

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
