import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import Container from "../../components/Container";
import Header from "../../modules/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <Container className="flex flex-col">
        <div className="h-15"></div>
        {children}
      </Container>
    </>
  );
}
