import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { validateRequest } from "../../utils/auth";
import "./globals.css";
import Header from "./modules/Header";
import { SessionProvider } from "./providers/Session.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionData = await validateRequest();
  console.log(sessionData);
  return (
    <html lang="en">
      <body className={`inter.className bg-background relative`}>
        <SessionProvider value={sessionData}>
          <Header />
          {children}
          <ToastContainer />
        </SessionProvider>
      </body>
    </html>
  );
}
