import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Container from "./components/Container";
import "./globals.css";
import Header from "./modules/Header";
import Provider from "./providers/index.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`bg-background relative`}
      >
        <Provider>
          <Container>
            <Header />
            {children}
          </Container>
          <ToastContainer />
        </Provider>
      </body>
    </html>
  );
}
